services: 
    db:
        image: postgres
        container_name: "pg_container"
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=test_db
        ports: 
            - "5432:5432"
    bi:
        image: metabase/metabase
        platform: linux/amd64
        ports:
            - "3000:3000"
        links:
        - db
        volumes:
        - "./volumes/.bi_volume:/metabase.db"