site_name: Resultados do Futebol desde 1920
icon: material/toggle-switch
theme:
  logo: img/code-xxl.png
  logo_color: white
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: green 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: green
repo_url: https://github.com/strangercacaus/resultados_do_futebol_desde_1980
repo_name: resultados_do_futebol_desde_1980

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stranger_cacaus
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/cacau/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/caueausec
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Boas Vindas: 'index.md'
  - Setup: Setup.md
  - Previews: Previews.md